// LoaderGenerator.ts
// Produces a small, standalone Lua "loader" script. The loader never
// contains a raw script URL and never has the payload embedded in it —
// it detects its own Place ID, sends {key, hwid, placeId} to Zer's
// /api/access endpoint, and only receives the actual source back once
// the server has verified everything server-side.

export interface LoaderOptions {
  title: string;
  accessUrl: string;
  getKeyStartUrl: string;
  getKeyStatusBaseUrl: string;
  keyFileName: string;
}

export function generateLoader(opts: LoaderOptions): string {
  const { title, accessUrl, getKeyStartUrl, getKeyStatusBaseUrl, keyFileName } = opts;

  return `-- ${title} — key system loader (generated by Zer)
local ZER_KEY_FILE = ${JSON.stringify(keyFileName)}
local ZER_ACCESS_URL = ${JSON.stringify(accessUrl)}
local ZER_GETKEY_START_URL = ${JSON.stringify(getKeyStartUrl)}
local ZER_GETKEY_STATUS_BASE = ${JSON.stringify(getKeyStatusBaseUrl)}

local HttpService = game:GetService("HttpService")

local function getHwid()
    return (gethwid and gethwid())
        or (get_hwid and get_hwid())
        or tostring(game:GetService("RbxAnalyticsService"):GetClientId())
end

local function httpPost(url, bodyTbl)
    local ok0, body = pcall(function() return HttpService:JSONEncode(bodyTbl) end)
    if not ok0 then return false, "Failed to encode request." end

    local req = http_request or request or (syn and syn.request) or (fluxus and fluxus.request)
    if not req then
        return false, "Your executor doesn't support HTTP requests."
    end

    local ok, res = pcall(function()
        return req({
            Url = url,
            Method = "POST",
            Headers = { ["Content-Type"] = "application/json" },
            Body = body,
        })
    end)
    if not ok or not res or not res.Body then
        return false, "Network error contacting the key server."
    end

    local ok2, decoded = pcall(function() return HttpService:JSONDecode(res.Body) end)
    if not ok2 then
        return false, "Bad response from the key server."
    end
    return true, decoded
end

local function httpGet(url)
    local req = http_request or request or (syn and syn.request) or (fluxus and fluxus.request)
    if not req then
        return false, "Your executor doesn't support HTTP requests."
    end
    local ok, res = pcall(function()
        return req({ Url = url, Method = "GET" })
    end)
    if not ok or not res or not res.Body then
        return false, "Network error contacting the key server."
    end
    local ok2, decoded = pcall(function() return HttpService:JSONDecode(res.Body) end)
    if not ok2 then
        return false, "Bad response from the key server."
    end
    return true, decoded
end

local REASONS = {
    NOT_FOUND = "Key not found.",
    REVOKED = "This key has been revoked.",
    EXPIRED = "This key has expired.",
    HWID_LOCKED = "This key is already locked to a different device.",
    WRONG_SCRIPT = "This key isn't valid for this game.",
    PLACE_NOT_SUPPORTED = "This game isn't supported yet.",
    SCRIPT_DISABLED = "This script is currently disabled.",
    RATE_LIMITED = "Too many attempts — wait a moment and try again.",
    BAD_REQUEST = "Invalid request.",
}

-- Requests and, if authorized, runs the protected script in one step.
-- Returns true on success, or false + a human-readable reason on failure.
local function requestAndRun(key)
    local ok, result = httpPost(ZER_ACCESS_URL, {
        key = key,
        hwid = getHwid(),
        placeId = tostring(game.PlaceId),
    })
    if not ok then
        return false, result
    end
    if not result.valid then
        return false, REASONS[result.reason] or "Access denied."
    end

    local ranOk, err = pcall(function()
        loadstring(result.source)()
    end)
    if not ranOk then
        warn("[Zer] Script error: " .. tostring(err))
    end
    return true
end

-- Starts a LootLabs "Get Key" session for this game and returns the link
-- to send the user to, plus a token to poll for completion.
local function startGetKey()
    local ok, result = httpPost(ZER_GETKEY_START_URL, { placeId = tostring(game.PlaceId) })
    if not ok then
        return false, result
    end
    if not result.token or not result.url then
        return false, result.error or "Couldn't start Get Key."
    end
    return true, result
end

-- Polls until the session completes, then returns the issued key.
local function pollGetKey(token, onTick)
    for _ = 1, 200 do -- ~10 minutes at 3s intervals
        task.wait(3)
        local ok, status = httpGet(ZER_GETKEY_STATUS_BASE .. token)
        if ok and status.status == "completed" and status.key then
            return status.key
        end
        if onTick then onTick() end
    end
    return nil
end

-- Try a cached key first
if isfile and isfile(ZER_KEY_FILE) then
    local saved = readfile(ZER_KEY_FILE):gsub("%s", "")
    local ok = requestAndRun(saved)
    if ok then
        return
    else
        pcall(delfile, ZER_KEY_FILE)
    end
end

-- No valid cached key — prompt for one
local gui = Instance.new("ScreenGui")
gui.Name = "ZerKeySystem"
gui.ResetOnSpawn = false
gui.Parent = (gethui and gethui()) or game:GetService("CoreGui")

local backdrop = Instance.new("Frame")
backdrop.Size = UDim2.new(1, 0, 1, 0)
backdrop.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
backdrop.BackgroundTransparency = 1
backdrop.BorderSizePixel = 0
backdrop.ZIndex = 0
backdrop.Parent = gui

local frame = Instance.new("Frame")
frame.Size = UDim2.new(0, 320, 0, 210)
frame.Position = UDim2.new(0.5, -160, 0.5, -105)
frame.BackgroundColor3 = Color3.fromRGB(18, 18, 22)
frame.BorderSizePixel = 0
frame.ClipsDescendants = false
frame.Parent = gui

local corner = Instance.new("UICorner")
corner.CornerRadius = UDim.new(0, 12)
corner.Parent = frame

local innerStroke = Instance.new("UIStroke")
innerStroke.Color = Color3.fromRGB(45, 48, 56)
innerStroke.Thickness = 1
innerStroke.Transparency = 0.2
innerStroke.Parent = frame

-- A slim rotating gradient ring around the frame edge — a common accent
-- in Roblox key-system UIs, built fresh here rather than borrowed.
local glowRing = Instance.new("Frame")
glowRing.Size = UDim2.new(1, 6, 1, 6)
glowRing.Position = UDim2.new(0, -3, 0, -3)
glowRing.BackgroundTransparency = 1
glowRing.ZIndex = frame.ZIndex - 1
glowRing.Parent = frame

local glowCorner = Instance.new("UICorner")
glowCorner.CornerRadius = UDim.new(0, 14)
glowCorner.Parent = glowRing

local glowStroke = Instance.new("UIStroke")
glowStroke.Thickness = 2
glowStroke.Transparency = 0.35
glowStroke.Parent = glowRing

local glowGradient = Instance.new("UIGradient")
glowGradient.Color = ColorSequence.new({
    ColorSequenceKeypoint.new(0, Color3.fromRGB(76, 130, 247)),
    ColorSequenceKeypoint.new(0.5, Color3.fromRGB(52, 211, 153)),
    ColorSequenceKeypoint.new(1, Color3.fromRGB(76, 130, 247)),
})
glowGradient.Parent = glowStroke

local header = Instance.new("Frame")
header.Size = UDim2.new(1, 0, 0, 46)
header.BackgroundTransparency = 1
header.Parent = frame

local titleLabel = Instance.new("TextLabel")
titleLabel.Text = ${JSON.stringify(title)}
titleLabel.Size = UDim2.new(1, -20, 0, 22)
titleLabel.Position = UDim2.new(0, 14, 0, 10)
titleLabel.BackgroundTransparency = 1
titleLabel.TextXAlignment = Enum.TextXAlignment.Left
titleLabel.TextColor3 = Color3.fromRGB(240, 240, 245)
titleLabel.Font = Enum.Font.GothamBold
titleLabel.TextSize = 16
titleLabel.Parent = header

local subtitleLabel = Instance.new("TextLabel")
subtitleLabel.Text = "Enter your key to continue"
subtitleLabel.Size = UDim2.new(1, -20, 0, 16)
subtitleLabel.Position = UDim2.new(0, 14, 0, 30)
subtitleLabel.BackgroundTransparency = 1
subtitleLabel.TextXAlignment = Enum.TextXAlignment.Left
subtitleLabel.TextColor3 = Color3.fromRGB(130, 134, 148)
subtitleLabel.Font = Enum.Font.Gotham
subtitleLabel.TextSize = 12
subtitleLabel.Parent = header

local divider = Instance.new("Frame")
divider.Size = UDim2.new(1, -28, 0, 1)
divider.Position = UDim2.new(0, 14, 0, 46)
divider.BackgroundColor3 = Color3.fromRGB(40, 43, 50)
divider.BorderSizePixel = 0
divider.Parent = frame

local inputHolder = Instance.new("Frame")
inputHolder.Size = UDim2.new(1, -28, 0, 38)
inputHolder.Position = UDim2.new(0, 14, 0, 58)
inputHolder.BackgroundColor3 = Color3.fromRGB(26, 27, 32)
inputHolder.BorderSizePixel = 0
inputHolder.Parent = frame

local inputCorner = Instance.new("UICorner")
inputCorner.CornerRadius = UDim.new(0, 8)
inputCorner.Parent = inputHolder

local inputStroke = Instance.new("UIStroke")
inputStroke.Color = Color3.fromRGB(48, 51, 60)
inputStroke.Thickness = 1
inputStroke.Transparency = 0.4
inputStroke.Parent = inputHolder

local input = Instance.new("TextBox")
input.PlaceholderText = "Paste your key here"
input.Size = UDim2.new(1, -20, 1, 0)
input.Position = UDim2.new(0, 10, 0, 0)
input.BackgroundTransparency = 1
input.TextColor3 = Color3.fromRGB(255, 255, 255)
input.PlaceholderColor3 = Color3.fromRGB(100, 104, 116)
input.Font = Enum.Font.Code
input.TextSize = 14
input.TextXAlignment = Enum.TextXAlignment.Left
input.ClearTextOnFocus = false
input.Text = ""
input.Parent = inputHolder

local status = Instance.new("TextLabel")
status.Text = ""
status.Size = UDim2.new(1, -28, 0, 30)
status.Position = UDim2.new(0, 14, 0, 100)
status.BackgroundTransparency = 1
status.TextColor3 = Color3.fromRGB(255, 110, 110)
status.Font = Enum.Font.Gotham
status.TextSize = 12
status.TextWrapped = true
status.TextXAlignment = Enum.TextXAlignment.Left
status.Parent = frame

local submit = Instance.new("TextButton")
submit.Text = "Submit"
submit.Size = UDim2.new(1, -28, 0, 34)
submit.Position = UDim2.new(0, 14, 0, 134)
submit.BackgroundColor3 = Color3.fromRGB(76, 130, 247)
submit.TextColor3 = Color3.fromRGB(255, 255, 255)
submit.Font = Enum.Font.GothamBold
submit.TextSize = 14
submit.AutoButtonColor = true
submit.Parent = frame

local submitCorner = Instance.new("UICorner")
submitCorner.CornerRadius = UDim.new(0, 8)
submitCorner.Parent = submit

local getKeyBtn = Instance.new("TextButton")
getKeyBtn.Text = "Get Key"
getKeyBtn.Size = UDim2.new(1, -28, 0, 34)
getKeyBtn.Position = UDim2.new(0, 14, 0, 172)
getKeyBtn.BackgroundColor3 = Color3.fromRGB(28, 30, 36)
getKeyBtn.TextColor3 = Color3.fromRGB(220, 222, 230)
getKeyBtn.Font = Enum.Font.GothamBold
getKeyBtn.TextSize = 14
getKeyBtn.AutoButtonColor = true
getKeyBtn.Parent = frame

local getKeyCorner = Instance.new("UICorner")
getKeyCorner.CornerRadius = UDim.new(0, 8)
getKeyCorner.Parent = getKeyBtn

local getKeyStroke = Instance.new("UIStroke")
getKeyStroke.Color = Color3.fromRGB(50, 53, 62)
getKeyStroke.Thickness = 1
getKeyStroke.Transparency = 0.3
getKeyStroke.Parent = getKeyBtn

-- Entrance animation: fade the backdrop in and pop the card in from a
-- slightly smaller, lower, transparent state.
local TweenService = game:GetService("TweenService")
local finalSize = frame.Size
local finalPos = frame.Position
frame.Size = UDim2.new(0, 288, 0, 189)
frame.Position = finalPos + UDim2.new(0, 16, 0, 16)
frame.BackgroundTransparency = 1
innerStroke.Transparency = 1
TweenService:Create(backdrop, TweenInfo.new(0.25), { BackgroundTransparency = 0.55 }):Play()
TweenService:Create(frame, TweenInfo.new(0.28, Enum.EasingStyle.Quint, Enum.EasingDirection.Out), {
    Size = finalSize, Position = finalPos, BackgroundTransparency = 0,
}):Play()
TweenService:Create(innerStroke, TweenInfo.new(0.4), { Transparency = 0.2 }):Play()

-- Slowly rotate the accent ring's gradient for a subtle "alive" feel.
task.spawn(function()
    while glowRing.Parent do
        glowGradient.Rotation = (glowGradient.Rotation + 1) % 360
        task.wait(0.03)
    end
end)

submit.MouseButton1Click:Connect(function()
    local key = input.Text:gsub("%s", "")
    if key == "" then
        status.Text = "Please enter a key."
        return
    end
    status.TextColor3 = Color3.fromRGB(200, 200, 200)
    status.Text = "Checking..."

    local ok, err = requestAndRun(key)
    if ok then
        if isfile then
            pcall(writefile, ZER_KEY_FILE, key)
        end
        gui:Destroy()
    else
        status.TextColor3 = Color3.fromRGB(255, 90, 90)
        status.Text = tostring(err)
    end
end)

getKeyBtn.MouseButton1Click:Connect(function()
    status.TextColor3 = Color3.fromRGB(200, 200, 200)
    status.Text = "Starting..."
    getKeyBtn.Active = false

    local ok, result = startGetKey()
    if not ok then
        status.TextColor3 = Color3.fromRGB(255, 90, 90)
        status.Text = tostring(result)
        getKeyBtn.Active = true
        return
    end

    if setclipboard then
        pcall(setclipboard, result.url)
        status.Text = "Link copied! Paste it in your browser, finish the tasks, and wait here."
    else
        status.Text = "Open this in your browser: " .. result.url
    end

    task.spawn(function()
        local key = pollGetKey(result.token, function()
            status.Text = "Still waiting for you to finish the tasks..."
        end)
        getKeyBtn.Active = true
        if key then
            status.TextColor3 = Color3.fromRGB(120, 220, 150)
            status.Text = "Got your key! Running..."
            input.Text = key
            local runOk = requestAndRun(key)
            if runOk then
                if isfile then pcall(writefile, ZER_KEY_FILE, key) end
                gui:Destroy()
            else
                status.TextColor3 = Color3.fromRGB(255, 90, 90)
                status.Text = "Got a key but it didn't work — try Submit manually."
            end
        else
            status.TextColor3 = Color3.fromRGB(255, 90, 90)
            status.Text = "Timed out waiting for task completion. Try again."
        end
    end)
end)
`;
}
