// LoaderGenerator.ts
// Produces a small, standalone Lua "loader" script. This is NOT run
// through the obfuscation pipeline — it's a thin key-check wrapper that,
// once a valid key is confirmed, loadstrings the actual (already
// obfuscated) payload from wherever it's hosted (Rubiš/Pastebin/GitHub).

export interface LoaderOptions {
  title: string;
  scriptUrl: string;
  checkUrl: string;
  keyFileName: string;
}

export function generateLoader(opts: LoaderOptions): string {
  const { title, scriptUrl, checkUrl, keyFileName } = opts;

  return `-- ${title} — key system loader (generated by P20)
local P20_KEY_FILE = ${JSON.stringify(keyFileName)}
local P20_CHECK_URL = ${JSON.stringify(checkUrl)}
local P20_SCRIPT_URL = ${JSON.stringify(scriptUrl)}

local HttpService = game:GetService("HttpService")

local function getHwid()
    return (gethwid and gethwid())
        or (get_hwid and get_hwid())
        or tostring(game:GetService("RbxAnalyticsService"):GetClientId())
end

local function httpPost(url, bodyTbl)
    local ok0, body = pcall(function() return HttpService:JSONEncode(bodyTbl) end)
    if not ok0 then return false, "Failed to encode request." end

    local req = http_request or request or (syn and syn.request) or (fluxus and fluxus.request)
    if not req then
        return false, "Your executor doesn't support HTTP requests."
    end

    local ok, res = pcall(function()
        return req({
            Url = url,
            Method = "POST",
            Headers = { ["Content-Type"] = "application/json" },
            Body = body,
        })
    end)
    if not ok or not res or not res.Body then
        return false, "Network error contacting the key server."
    end

    local ok2, decoded = pcall(function() return HttpService:JSONDecode(res.Body) end)
    if not ok2 then
        return false, "Bad response from the key server."
    end
    return true, decoded
end

local REASONS = {
    NOT_FOUND = "Key not found.",
    REVOKED = "This key has been revoked.",
    EXPIRED = "This key has expired.",
    HWID_LOCKED = "This key is already locked to a different device.",
    BAD_REQUEST = "Invalid request.",
}

local function checkKey(key)
    local ok, result = httpPost(P20_CHECK_URL, { key = key, hwid = getHwid() })
    if not ok then
        return false, result
    end
    if result.valid then
        return true
    end
    return false, REASONS[result.reason] or "Invalid key."
end

local function runScript()
    local ok, err = pcall(function()
        loadstring(game:HttpGet(P20_SCRIPT_URL))()
    end)
    if not ok then
        warn("[P20] Failed to load script: " .. tostring(err))
    end
end

-- Try a cached key first
if isfile and isfile(P20_KEY_FILE) then
    local saved = readfile(P20_KEY_FILE):gsub("%s", "")
    local ok = checkKey(saved)
    if ok then
        runScript()
        return
    else
        pcall(delfile, P20_KEY_FILE)
    end
end

-- No valid cached key — prompt for one
local Players = game:GetService("Players")

local gui = Instance.new("ScreenGui")
gui.Name = "P20KeySystem"
gui.ResetOnSpawn = false
gui.Parent = (gethui and gethui()) or game:GetService("CoreGui")

local frame = Instance.new("Frame")
frame.Size = UDim2.new(0, 300, 0, 140)
frame.Position = UDim2.new(0.5, -150, 0.5, -70)
frame.BackgroundColor3 = Color3.fromRGB(20, 20, 24)
frame.BorderSizePixel = 0
frame.Parent = gui

local corner = Instance.new("UICorner")
corner.CornerRadius = UDim.new(0, 8)
corner.Parent = frame

local titleLabel = Instance.new("TextLabel")
titleLabel.Text = ${JSON.stringify(title)} .. " — Enter Key"
titleLabel.Size = UDim2.new(1, 0, 0, 30)
titleLabel.BackgroundTransparency = 1
titleLabel.TextColor3 = Color3.fromRGB(230, 230, 230)
titleLabel.Font = Enum.Font.GothamBold
titleLabel.TextSize = 16
titleLabel.Parent = frame

local input = Instance.new("TextBox")
input.PlaceholderText = "Paste your key here"
input.Size = UDim2.new(1, -20, 0, 36)
input.Position = UDim2.new(0, 10, 0, 40)
input.BackgroundColor3 = Color3.fromRGB(30, 30, 36)
input.TextColor3 = Color3.fromRGB(255, 255, 255)
input.Font = Enum.Font.Code
input.TextSize = 14
input.ClearTextOnFocus = false
input.Text = ""
input.Parent = frame

local status = Instance.new("TextLabel")
status.Text = ""
status.Size = UDim2.new(1, -20, 0, 20)
status.Position = UDim2.new(0, 10, 0, 82)
status.BackgroundTransparency = 1
status.TextColor3 = Color3.fromRGB(255, 90, 90)
status.Font = Enum.Font.Gotham
status.TextSize = 12
status.TextWrapped = true
status.Parent = frame

local submit = Instance.new("TextButton")
submit.Text = "Submit"
submit.Size = UDim2.new(1, -20, 0, 30)
submit.Position = UDim2.new(0, 10, 0, 104)
submit.BackgroundColor3 = Color3.fromRGB(76, 130, 247)
submit.TextColor3 = Color3.fromRGB(255, 255, 255)
submit.Font = Enum.Font.GothamBold
submit.TextSize = 14
submit.AutoButtonColor = true
submit.Parent = frame

submit.MouseButton1Click:Connect(function()
    local key = input.Text:gsub("%s", "")
    if key == "" then
        status.Text = "Please enter a key."
        return
    end
    status.TextColor3 = Color3.fromRGB(200, 200, 200)
    status.Text = "Checking..."

    local ok, err = checkKey(key)
    if ok then
        if isfile then
            pcall(writefile, P20_KEY_FILE, key)
        end
        gui:Destroy()
        runScript()
    else
        status.TextColor3 = Color3.fromRGB(255, 90, 90)
        status.Text = tostring(err)
    end
end)
`;
}
